# Generated by Django 4.0.2 on 2022-02-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_commentmodel_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.commentmodel",
            ),
        ),
    ]
