# Generated by Django 4.0.2 on 2022-02-27 03:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_alter_commentmodel_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, default=list, size=10
            ),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="replies",
                to="comments.commentmodel",
            ),
        ),
    ]
