# Generated by Django 4.0.2 on 2022-03-08 16:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_feedmodel_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedmodel",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024), default=list, size=None
            ),
        ),
    ]
