# Generated by Django 4.0.2 on 2022-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
