# Generated by Django 4.0.2 on 2022-02-26 10:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_alter_feedmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(choices=[('COMMENT', 'Comment'), ('REVIEW', 'Review'), ('ANSWER', 'Answer to review or comment')], max_length=7)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('text', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('likes_amount', models.IntegerField(default=0)),
                ('feed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feedmodel')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
