# Generated by Django 4.0.2 on 2022-02-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feedmodel_type'),
        ('comments', '0004_alter_commentmodel_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='feed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.feedmodel'),
        ),
    ]
