# Generated by Django 4.0.2 on 2022-02-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_alter_commentmodel_feed_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
