# Generated by Django 4.0.2 on 2022-02-05 07:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('AR', 'Article'), ('AS', 'Sponsored article'), ('EV', 'Event'), ('ES', 'Sponsored event')], max_length=2)),
                ('text', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=1024)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=10)),
                ('date', models.DateTimeField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('likes_amount', models.IntegerField(default=0)),
                ('views_amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
    ]
