# Generated by Django 4.0.2 on 2022-03-08 10:45

from django.db import migrations, models
import django.db.models.deletion

from categories.models import CategoryModel


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categorymodel_deleted"),
        ("clubs", "0002_clubmodel_searchable_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="categories.categorymodel",
                default=None,
            ),
            preserve_default=False,
        ),
    ]
