# Generated by Django 4.0.2 on 2022-03-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmodel_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('photo', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('phone', models.CharField(max_length=256, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='clubs.clubmodel')),
            ],
        ),
    ]
