# Generated by Django 4.0.2 on 2022-03-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorymodel_deleted'),
        ('clubs', '0003_clubmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.categorymodel'),
        ),
    ]
