# Generated by Django 4.0.2 on 2022-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_communicationobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
    ]
