# Generated by Django 4.0.2 on 2022-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_clubmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
    ]
