# Generated by Django 4.0.2 on 2024-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_clubmodel_latitude_alter_clubmodel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
